"""create creator profile table

Revision ID: 12f10a85d09e
Revises: 45baa27d1453
Create Date: 2026-07-23 23:04:20.767022

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f10a85d09e'
down_revision: Union[str, Sequence[str], None] = '45baa27d1453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    creator_table = op.create_table(
        'creator_profile',
        sa.Column('id', sa.String(length=1), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('father_name', sa.String(length=100), nullable=False),
        sa.Column('mother_name', sa.String(length=100), nullable=False),
        sa.Column('girlfriend_name', sa.String(length=100), nullable=False),
        sa.Column('family_lineage', sa.Text(), nullable=True),
        sa.Column('birthplace', sa.String(length=100), nullable=False),
        sa.Column('ancestral_roots', sa.String(length=100), nullable=False),
        sa.Column('hometown', sa.String(length=100), nullable=False),
        sa.Column('education_background', sa.Text(), nullable=True),
        sa.Column('graduation_year', sa.String(length=4), nullable=False),
        sa.Column('graduation_degree', sa.String(length=100), nullable=False),
        sa.Column('personality', sa.Text(), nullable=True),
        sa.Column('hobbies', sa.Text(), nullable=True),
        sa.Column('dreams', sa.Text(), nullable=True),
        sa.Column('linkedin_url', sa.String(length=500), nullable=True),
        sa.Column('github_url', sa.String(length=500), nullable=True),
        sa.Column('instagram_url', sa.String(length=500), nullable=True),
        sa.Column('twitter_url', sa.String(length=500), nullable=True),
        sa.Column('raghvi_name_origin', sa.Text(), nullable=True),
        sa.Column('creation_purpose', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('last_sync_social', sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )

    # Seed initial creator profile
    op.bulk_insert(
        creator_table,
        [
            {
                "id": "1",
                "name": "Vishal Singh Kushwaha",
                "father_name": "Shyam Singh",
                "mother_name": "Urmila Devi",
                "girlfriend_name": "Disha Saini",
                "family_lineage": "Descendant of Bhagwan Rama's son Kush",
                "birthplace": "Kanpur",
                "ancestral_roots": "Rajasthan",
                "hometown": "Ghaziabad",
                "education_background": "BCA Graduate (2026)",
                "graduation_year": "2026",
                "graduation_degree": "BCA",
                "personality": "Introvert, thoughtful, disciplined, independent",
                "hobbies": "Weight lifting, reading, exploring, astronomy, space, nature",
                "dreams": "Achieving greatness while building a peaceful, loving family",
                "github_url": "https://github.com/Smiling-Hacker01",
                "linkedin_url": "https://www.linkedin.com/in/sdevsk/",
                "instagram_url": "https://www.instagram.com/eccedentesiast_vsk/",
                "twitter_url": None,
                "raghvi_name_origin": (
                    "Feminine form of Raghvendra, and the same special name given to future "
                    "mother Disha Saini"
                ),
                "creation_purpose": "Created so that no one ever has to feel alone",
                "created_at": datetime.utcnow(),
                "updated_at": datetime.utcnow(),
                "last_sync_social": None,
            }
        ]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('creator_profile')
    # ### end Alembic commands ###
