"""create memories table

Revision ID: 45baa27d1453
Revises: b5faaa39919b
Create Date: 2026-07-22 13:12:04.049982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45baa27d1453'
down_revision: Union[str, Sequence[str], None] = 'b5faaa39919b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memories',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memories_user_id'), 'memories', ['user_id'], unique=False)
    op.create_index('ix_memory_created_desc', 'memories', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_memory_user_approved', 'memories', ['user_id', 'approved_at'], unique=False)
    op.create_index('ix_memory_user_sensitive', 'memories', ['user_id', 'is_sensitive'], unique=False)
    op.drop_constraint(op.f('uq_conversations_user_id'), 'conversations', type_='unique')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_conversations_user_id'), 'conversations', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('ix_memory_user_sensitive', table_name='memories')
    op.drop_index('ix_memory_user_approved', table_name='memories')
    op.drop_index('ix_memory_created_desc', table_name='memories')
    op.drop_index(op.f('ix_memories_user_id'), table_name='memories')
    op.drop_table('memories')
    # ### end Alembic commands ###
