"""create subscription and voice tables

Revision ID: 8af8727cf82a
Revises: 8e2ddcc87da0
Create Date: 2026-07-27 09:47:36.265263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8af8727cf82a'
down_revision: Union[str, Sequence[str], None] = '8e2ddcc87da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_voices',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('voice_name', sa.String(length=200), nullable=False),
    sa.Column('voice_id', sa.String(length=500), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_voices_language'), 'system_voices', ['language'], unique=False)
    op.create_table('user_voices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('voice_type', sa.String(length=20), nullable=False),
    sa.Column('voice_id', sa.String(length=500), nullable=False),
    sa.Column('voice_name', sa.String(length=200), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('languages', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('subscription_plan_id', sa.String(length=50), nullable=True),
    sa.Column('expires_with_subscription', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('audio_sample_url', sa.String(length=500), nullable=True),
    sa.Column('audio_sample_duration', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_voice_active', 'user_voices', ['user_id', 'is_active'], unique=False)
    op.create_index('ix_user_voice_expires', 'user_voices', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_user_voices_user_id'), 'user_voices', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_voices_user_id'), table_name='user_voices')
    op.drop_index('ix_user_voice_expires', table_name='user_voices')
    op.drop_index('ix_user_voice_active', table_name='user_voices')
    op.drop_table('user_voices')
    op.drop_index(op.f('ix_system_voices_language'), table_name='system_voices')
    op.drop_table('system_voices')
    # ### end Alembic commands ###
