"""create reminders table

Revision ID: 8e2ddcc87da0
Revises: 1e0df95b33b6
Create Date: 2026-07-26 18:06:12.246715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e2ddcc87da0'
down_revision: Union[str, Sequence[str], None] = '1e0df95b33b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('reminder_type', sa.String(length=20), nullable=True),
    sa.Column('reminder_time', sa.DateTime(), nullable=False),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reminder_time', 'reminders', ['reminder_time'], unique=False)
    op.create_index('ix_reminder_user_sent', 'reminders', ['user_id', 'sent'], unique=False)
    op.create_index(op.f('ix_reminders_task_id'), 'reminders', ['task_id'], unique=False)
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_index(op.f('ix_reminders_task_id'), table_name='reminders')
    op.drop_index('ix_reminder_user_sent', table_name='reminders')
    op.drop_index('ix_reminder_time', table_name='reminders')
    op.drop_table('reminders')
    # ### end Alembic commands ###
