"""add unique constraint on conversations user_id

Revision ID: b5faaa39919b
Revises: defaf42c39c7
Create Date: 2026-07-21 12:24:20.790807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5faaa39919b'
down_revision: Union[str, Sequence[str], None] = 'defaf42c39c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop existing conversation if duplicate (to avoid IntegrityError on constraint creation)
    # PostgreSQL cannot run MIN() on UUIDs directly, so we cast to string and back
    op.execute("DELETE FROM conversations WHERE id NOT IN (SELECT CAST(MIN(CAST(id AS VARCHAR)) AS UUID) FROM conversations GROUP BY user_id)")
    
    # Drop foreign key constraint before altering column type
    op.drop_constraint('messages_conversation_id_fkey', 'messages', type_='foreignkey')
    
    op.alter_column('conversations', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('conversations', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
               
    op.create_unique_constraint('uq_conversations_user_id', 'conversations', ['user_id'])
    
    op.alter_column('messages', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
               
    # Re-create foreign key constraint
    op.create_foreign_key(
        'messages_conversation_id_fkey', 
        'messages', 
        'conversations', 
        ['conversation_id'], 
        ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop foreign key constraint
    op.drop_constraint('messages_conversation_id_fkey', 'messages', type_='foreignkey')
    
    op.alter_column('messages', 'conversation_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('messages', 'id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('conversations', 'user_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('conversations', 'id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_constraint('uq_conversations_user_id', 'conversations')
    
    # Re-create foreign key constraint
    op.create_foreign_key(
        'messages_conversation_id_fkey', 
        'messages', 
        'conversations', 
        ['conversation_id'], 
        ['id'],
        ondelete='CASCADE'
    )
    # ### end Alembic commands ###
